### ISSUE TITLE
Enable dark mode for Documentation Page

### ISSUE THREAD

**Issue by JaynouOliver** [kedro-org/awesome-kedro#23]
https://docs.kedro.org/en/stable/#
![image](https://github.com/kedro-org/awesome-kedro/assets/88646338/ca482a72-0cd7-4fca-a8a9-e9019788bd06)

**Comment by astrojuanlu** [comment]
Hi @JaynouOliver ! Could you please open this issue on kedro-org/kedro and describe a bit why would you like the Kedro docs to have a dark mode?

**Comment by JaynouOliver** [comment]
Sure I will do that. It is quite difficult to view the page in light mode in dark. Although we all use an extension but it is better to have a dark mode button that can switch the color

**Comment by astrojuanlu** [comment]
Closing this one for now, since it won't be actioned on this repo

**Comment by JaynouOliver** [comment]
Will it be accepted on the other repo?
